name: Build
on: [push, pull_request]

jobs:
  build:
    name: mac
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [x64, arm64]
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 16
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run make
